# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81e4916b87a1c689676294ef8106aa10b3e6f308e0f6df750fd1525588bc35ef64c7c4cefe2443c248fb9bdcdee295d475245a62a94c758a6b4a5d6f8d8e55f9

test:
  secret_key_base: 57e7d0b17dc0bd38f66069d32ebffddd834a2088476bbed12f7896812d8af6b62610fe7d571702002b2a13438d4a689a698730752b310faae5f382dce8d4a181

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
